services:
  - type: web
    name: aiges
    env: python
    buildCommand: ./build.sh
    # --preload is critical for your APScheduler lock logic
    startCommand: gunicorn config.wsgi:application --preload
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings
      - key: DEBUG
        value: 'False'
      - fromDatabase:
          name: health_db
          property: connectionString

databases:
  - name: health_db
    databaseName: hospital_records
    user: samuel
    plan: free 