# Generated by Django 6.0.2 on 2026-02-21 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hypertension', models.IntegerField(default=0, help_text='0 for No, 1 for Yes')),
                ('heart_disease', models.IntegerField(default=0, help_text='0 for No, 1 for Yes')),
                ('avg_glucose_level', models.FloatField(blank=True, null=True)),
                ('bmi', models.FloatField(blank=True, null=True)),
                ('ever_married_Yes', models.IntegerField(default=0, help_text='0 for No, 1 for Yes')),
                ('work_type_Private', models.IntegerField(default=0, help_text='0 for No, 1 for Yes')),
                ('Residence_type_Urban', models.IntegerField(default=0, help_text='0 for Rural, 1 for Urban')),
                ('smoking_status_smokes', models.IntegerField(default=0, help_text='0 for No, 1 for Yes')),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medical_record', to='patients.patient')),
            ],
        ),
        migrations.CreateModel(
            name='VitalSignLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('systolic_bp', models.IntegerField()),
                ('diastolic_bp', models.IntegerField()),
                ('heart_rate', models.IntegerField()),
                ('daily_steps', models.IntegerField()),
                ('sleep_hours', models.FloatField()),
                ('medications', models.TextField(blank=True, help_text='Medications currently taken', null=True)),
                ('signs_and_symptoms', models.TextField(blank=True, help_text='Any notable symptoms', null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vital_logs', to='patients.patient')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
